/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kn.uni.hahn

import kn.uni.hahn.gui.MainWindow

fun main() {
    val window = MainWindow()
    window.isVisible = true
}